from __future__ import annotations

from dataclasses import dataclass
from time import perf_counter
from typing import Callable

import numpy as np
from scipy.stats import qmc

from diffusion_coverage.geometry.robot_surface_metric import (
    compute_robot_surface_metric,
    estimate_surface_contact_differential,
)
from diffusion_coverage.robot.execution_cost import compute_joint_execution_cost
from diffusion_coverage.robot.task_kinematics import evaluate_task_kinematics_5d


@dataclass(frozen=True)
class FormulationContract:
    name: str
    optimize_surface: bool
    optimize_configuration: bool


FORMULATIONS = {
    "F0": FormulationContract("F0", False, False),
    "F1": FormulationContract("F1", False, True),
    "F2": FormulationContract("F2", True, False),
    "F3": FormulationContract("F3", True, True),
}


@dataclass(frozen=True)
class CoupledLiftResult:
    found: bool
    q_path: np.ndarray | None
    joint_length: float | None
    failure_reason: str | None
    expanded_states: int
    generated_candidates: int
    retained_states: tuple[int, ...]
    solve_time: float


def frozen_surface_candidate_bank(count: int, maximum_displacement: float, seed: int) -> np.ndarray:
    if count < 1 or maximum_displacement <= 0.0:
        raise ValueError("candidate count and displacement must be positive")
    power = int(np.ceil(np.log2(count)))
    samples = qmc.Sobol(d=6, scramble=True, seed=seed).random_base2(power)[:count]
    values = (2.0 * samples - 1.0).reshape(count, 3, 2) * maximum_displacement
    norms = np.linalg.norm(values, axis=2)
    scale = np.minimum(1.0, maximum_displacement / np.maximum(norms, 1e-15))
    return values * scale[:, :, None]


def minimum_cost_layered_lift(
    robot,
    desired_positions: np.ndarray,
    desired_axes: np.ndarray,
    q_start: np.ndarray,
    q_end: np.ndarray,
    *,
    characteristic_length: float,
    sigma_safe: float,
    axis_tolerance: float,
    position_tolerance: float,
    maximum_joint_step: float,
    beam_width: int,
    null_offsets: tuple[float, ...],
    deduplication_radius: float,
    ik_max_iterations: int,
    reference_q_path: np.ndarray | None = None,
) -> CoupledLiftResult:
    """Numerically minimize J_q over a deterministic local layered IK graph.

    The first and last configurations are fixed. Interior candidates are generated by
    perturbing each parent's one-dimensional normalized-task null direction and projecting
    back to the requested task pose through IK. This is an optimum only over the retained
    numerical beam graph.
    """

    started = perf_counter()
    positions = np.asarray(desired_positions, dtype=np.float64)
    axes = np.asarray(desired_axes, dtype=np.float64)
    start = np.asarray(q_start, dtype=np.float64)
    end = np.asarray(q_end, dtype=np.float64)
    if positions.ndim != 2 or positions.shape[1] != 3 or axes.shape != positions.shape or len(positions) < 2:
        raise ValueError("desired task path must have shape [T,3]")
    if start.shape != (6,) or end.shape != (6,) or beam_width < 1:
        raise ValueError("invalid endpoint or beam width")
    reference = None if reference_q_path is None else np.asarray(reference_q_path, dtype=np.float64)
    if reference is not None and reference.shape != (len(positions), 6):
        raise ValueError("reference_q_path must match the task path")

    # Each state is (q, cumulative cost, full q prefix).
    states: list[tuple[np.ndarray, float, list[np.ndarray]]] = [(start.copy(), 0.0, [start.copy()])]
    retained = [1]
    expanded = 0
    generated = 0
    for index in range(1, len(positions) - 1):
        children: list[tuple[np.ndarray, float, list[np.ndarray]]] = []
        for parent_q, parent_cost, prefix in states:
            expanded += 1
            task = evaluate_task_kinematics_5d(robot, parent_q, characteristic_length=characteristic_length)
            null = normalized_task_null_direction(task.normalized_jacobian_5)
            seeds = [np.clip(parent_q + offset * null, robot.lower_limits, robot.upper_limits) for offset in null_offsets]
            if reference is not None:
                seeds.append(reference[index])
            for seed in seeds:
                candidate = robot.solve_ik(
                    positions[index], axes[index], seed,
                    position_tolerance=min(position_tolerance, 1e-3),
                    axis_tolerance=axis_tolerance, max_iterations=ik_max_iterations,
                )
                generated += 1
                if candidate is None or not candidate.collision_free:
                    continue
                q_value = np.asarray(candidate.q, dtype=np.float64)
                if float(np.max(np.abs(q_value - parent_q))) > maximum_joint_step:
                    continue
                task_value = evaluate_task_kinematics_5d(robot, q_value, characteristic_length=characteristic_length)
                if task_value.sigma_min_5 < sigma_safe:
                    continue
                edge = robot.check_task_transition(
                    parent_q, q_value, positions[index - 1 : index + 1], axes[index - 1 : index + 1],
                    maximum_joint_step=maximum_joint_step, minimum_manipulability=0.0,
                    position_tolerance=position_tolerance, axis_tolerance=axis_tolerance,
                    allow_equivalent_end=False,
                )
                if not edge.feasible:
                    continue
                cost = parent_cost + float(np.linalg.norm(q_value - parent_q))
                children.append((q_value, cost, prefix + [q_value]))
        states = retain_low_cost_states(children, beam_width, deduplication_radius)
        retained.append(len(states))
        if not states:
            return CoupledLiftResult(False, None, None, "layered_q_search_exhaustion", expanded, generated, tuple(retained), perf_counter() - started)

    finals: list[tuple[np.ndarray, float, list[np.ndarray]]] = []
    for parent_q, parent_cost, prefix in states:
        expanded += 1
        edge = robot.check_task_transition(
            parent_q, end, positions[-2:], axes[-2:], maximum_joint_step=maximum_joint_step,
            minimum_manipulability=0.0, position_tolerance=position_tolerance,
            axis_tolerance=axis_tolerance, allow_equivalent_end=False,
        )
        generated += 1
        if not edge.feasible:
            continue
        end_task = evaluate_task_kinematics_5d(robot, end, characteristic_length=characteristic_length)
        if end_task.sigma_min_5 < sigma_safe:
            continue
        finals.append((end, parent_cost + float(np.linalg.norm(end - parent_q)), prefix + [end.copy()]))
    if not finals:
        return CoupledLiftResult(False, None, None, "terminal_configuration_unreachable", expanded, generated, tuple(retained + [0]), perf_counter() - started)
    selected = min(finals, key=lambda item: item[1])
    q_path = np.asarray(selected[2], dtype=np.float64)
    joint_length = compute_joint_execution_cost((q_path,)).weighted_joint_length
    return CoupledLiftResult(True, q_path, joint_length, None, expanded, generated, tuple(retained + [len(finals)]), perf_counter() - started)


def normalized_task_null_direction(jacobian: np.ndarray) -> np.ndarray:
    matrix = np.asarray(jacobian, dtype=np.float64)
    if matrix.shape != (5, 6):
        raise ValueError("normalized task Jacobian must have shape [5,6]")
    _, _, vh = np.linalg.svd(matrix, full_matrices=True)
    direction = vh[-1].copy()
    direction /= np.linalg.norm(direction)
    pivot = int(np.argmax(np.abs(direction)))
    if direction[pivot] < 0.0:
        direction *= -1.0
    return direction


def retain_low_cost_states(states, maximum_count: int, deduplication_radius: float):
    output = []
    for state in sorted(states, key=lambda item: (item[1], tuple(item[0]))):
        if any(np.linalg.norm(state[0] - existing[0]) < deduplication_radius for existing in output):
            continue
        output.append(state)
        if len(output) == maximum_count:
            break
    return output


def select_verified_incumbent(current: dict, candidate: dict) -> tuple[dict, bool]:
    if not candidate.get("admitted", False) or candidate.get("J_q") is None:
        return current, False
    if float(candidate["J_q"]) + 1e-12 >= float(current["J_q"]):
        return current, False
    return candidate, True


def tangent_metric_diagnostics(
    robot,
    surface,
    transform: np.ndarray,
    q_path: np.ndarray,
    points_surface: np.ndarray,
    *,
    characteristic_length: float,
    sigma_safe: float,
    finite_difference_step: float,
    sample_count: int,
) -> dict[str, float]:
    q = np.asarray(q_path, dtype=np.float64); points = np.asarray(points_surface, dtype=np.float64)
    indices = np.unique(np.linspace(0, len(q) - 2, min(sample_count, len(q) - 1), dtype=int))
    total_lg = 0.0; logs = []; cheap = []; expensive = []
    for index in indices:
        task = evaluate_task_kinematics_5d(robot, q[index], characteristic_length=characteristic_length)
        contact = estimate_surface_contact_differential(
            surface, points[index], transform, task.axis_basis,
            characteristic_length=characteristic_length, finite_difference_step=finite_difference_step,
        )
        metric = compute_robot_surface_metric(task, contact.task_differential, minimum_singular_value=sigma_safe)
        delta_base = transform[:3, :3] @ (points[index + 1] - points[index])
        delta_xi = contact.tangent_basis.T @ delta_base
        total_lg += float(np.sqrt(max(delta_xi @ metric.matrix @ delta_xi, 0.0)))
        norm = float(np.linalg.norm(delta_xi))
        if norm > 1e-12:
            tangent = delta_xi / norm
            cheap.append(abs(float(tangent @ metric.eigenvectors[:, 0])))
            expensive.append(abs(float(tangent @ metric.eigenvectors[:, 1])))
        logs.append(metric.log_kappa_R)
    # Scale sampled metric length to the full path by sample edge-length coverage.
    sampled_surface = sum(float(np.linalg.norm(points[i + 1] - points[i])) for i in indices)
    full_surface = float(np.linalg.norm(np.diff(points, axis=0), axis=1).sum())
    scale = full_surface / max(sampled_surface, 1e-15)
    return {
        "integrated_L_G_diagnostic": total_lg * scale,
        "median_log_kappa_R": float(np.median(logs)),
        "mean_abs_alignment_cheap": float(np.mean(cheap)) if cheap else np.nan,
        "mean_abs_alignment_expensive": float(np.mean(expensive)) if expensive else np.nan,
    }


def formulation_runner_contract(name: str) -> FormulationContract:
    return FORMULATIONS[name]
